language: php
php: 5.6
source_key: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpQcm9jLVR5cGU6IDQsRU5DUllQVEVECkRFSy1JbmZvOiBBRVMtMTI4LUNCQywxMzNFMTc0MUU4Nzg1QUIyQjRFNDlENDBCRUYwMDc5MgoKMVM2Mmdmd25qRCtpQlNaR01TVUlxUUNEdHdzUmhPZjVJRnJxcU9YZFYvNTE0Nzh6QVB5aFNIbmpVaE95UDhIYgozQkhpL0MwMXZlcnB3ejA1eEJsOWpYL3ltOWJsYjIzbVgzNm8xTjQycmxsQ0I2T3AvU2dXVUxxa0NRUUU3elFiCmNpNHJVWlNzN2E2aUliRElUZE9hK0pDZk9KeGFmNjNPQkJ2L3dKaUQzVmhiM3Q2ZytjeFN2Qkdyb2gzZGYzRUUKZXkyKzNwaGhlcUlOQjBEUXA4ZTlmMWtKK0g0bHlXWkR4SnhmV0F3YlNzRWJjZlVoMGN5L3ZuckxSYTNhTUZWcgoyWDUzTEo3V3A2dmRBOU1EODhoSi9uNU5FSXkyb0JsSEl2amdML1lYQWJMZ0lyME0zeFE3VldnUEJuTmFuRXpyCmlZWVFjclE2SkppVkM4ZzZVbG9pdGtqN2JyZkJ0UjFwdXlIeGFHYUJyZ0ZtWXFVa2paZVNkeWMxdWxqeCtXd08KejlsNjNTcW9oWTNMa0NlVEVpQ2FUNDNSdU4ybW1oREpOTWVEb3JPWnJoNmpyY2V5RWhoRlBmcEU2TjF3OUpENApUTzBYaFVHSUhGQ2hHdWJUWXJtMTBwandURnBTczVVR2t3K0ZPcUl3dVorYURiQVNWd3Y1OFc3NUNETjVmTEljCjRDdmtSWXluOFBEOGxBMUZiWjhHSXRveFZjU3FaOVNlelQyMmdBOEtjQnVUbzFmOGsxQ1BBOGNrVnF6Zm1BVFYKNEFmMFBkSVJsMENCYmFtbUtqdERCZjJpK1R1U21UcjNkUXlmWkZJUklZQTA2Zkt1azJvemErY2c1elFwSkUraAo4a1RmNWU2UHhCT29sbDAyOEtiZ0hoWHVDREV4WVQ5VnN1eFpaRUZTUU1KM0hOUyttcndCM2hyVGExSTcrVWlBCmdCZTBSWXRIL2FlbDJ5MmplYkMrZVdKRTdSc2p2Z242VytTK1I3b3BIcTBxVHd5UmF4RzFVQkNLelBUbk1ERC8KaXpZUFdoR2pkYU0yZ28xeVF5RVNmbm5oRWZOcHNYUklIVGtJZjlhT3JWVm15eTk0ekVZUElsV1FaVFlKbmdwNQpLRXhmME9GLzRDbXBqQkpwRm1tZ1lESkRtK3RheU9YbG9tYWYvbG1VbmJkcFQxNEpXcGd3NmdheHdJZHMvOFBhCnYxUnp5NEF5K1E2N3F4aGtkQStXNDJGOTk4a0kyT2ZBNGwvSVVHYjhla3ZYNU9JVkNhMEV0RjViZkEwRERVUncKN1pmSkVJaVdtUEJQaXQ4dHBPZ0RNdUl5di9VZktDbVpRdFdnNTJFWG1qaCsvaVovb3ozYUZ3VENzaWd2ZmxXSApqRThQcC9vQjA5TlBJcFB2ZG04YVp4dVUvR3lUQ1J1TkhhdjNhQzlvUnVZWlR1RFBwMXBEMXNBbTR4NmdqYWxqCnVFOFpCQm9teXprVjFuU2NjSi9UNG9GdXI4amd1MlF2b3BxRGRsZDJlVUZGM2VPVWNEVElYTnYxc2MzWlo5RzAKeWRCTGpRZkh6STY4MVk4VVpGSy9ITVA5a1VXQ0hYVWdLanE5ZVhvNTlLY21wQVd4OXV1WVdYdHA5U1JoNVptNQozd1pYV1VaSE9YWDFFQU5rNm5USlpDajVZVjFsNkV1YUQ3anphbmQ2ZHhUWDRYOENSMmViWlJIUUFxQmg4MXdvCnJoaUs2akJ5OGRRK3lmek4vMVlhZnJuaUNQNU0wcEFWdjNmY2VqUlYzUnI1UlUvWlZ5NVVRU2l6RWxTTEFZdmQKMHFXbmlCd0d5WVdFU0Jic2pVODJPak5pV3JWbUh3bWVGbXBMd2ZUNkN1NEZuSVlJYlNxQ0RLUGhHT0pTbjBKbgpTWklpN2pTNjJCVVdnbjZiUWRvUWllSWhwaXlIek5lTER5ZjhNZGRrU1Jqd01JM3BYQVdtSDdtbEk0dUFTanB0ClZXbExTM3RvYzF4SXA2MndDTE5ic25MNkJVd2p0bVBGdFFCOUdrSkdSQUZoY1U1NzVTL1V6WEFwMlZoZnRCVDkKamsxcDFtSTdSYWZwRUhneDl0N1c1NnM4MlpVQ1hkZm5makFUUEozSUs1RHZ1WWdzWnIrWE53cCs3Q1RGWWEwNAotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo="
env:
  global:
    - PUUID='0759f9d3-f975-4154-a0ec-7a94bd6e73b7'
    - PNAME='drupers-testing'
    - PSOURCE='dev'
    - PEMAIL='viktor.lovas@gmail.com'
    - PPASS='pantheontest'
    - PSITE=$(cat /dev/urandom | tr -cd 'a-z0-9' | head -c 4)
    - PSITE="ci$TRAVIS_BUILD_NUMBER-$PSITE"
    - PHOST="https://$TRAVIS_BRANCH-$PNAME.pantheonsite.io"
install:
  - echo "StrictHostKeyChecking no" > ~/.ssh/config
  - composer global require drush/drush:7.0.0
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - git clone https://github.com/pantheon-systems/terminus.git $HOME/.drush/terminus
  - cd $HOME/.drush/terminus
  - composer update --no-dev
  - drush cc drush
  # Install additional test dependencies here (like Casper, Behat, etc).
before_script:
  - drush pauth $PEMAIL --password=$PPASS
  - cd $TRAVIS_BUILD_DIR
  - git checkout -b $PSITE
  - git remote add pantheon ssh://codeserver.dev.$PUUID@codeserver.dev.$PUUID.drush.in:2222/~/repository.git
  - git push --force pantheon $PSITE
  - drush psite-ecreate $PUUID $PSITE --source=$PSOURCE || true
  - drush paliases
  - drush cc drush
  - cd $HOME
  - drush @pantheon.$PNAME.$PSITE updb -y --strict=0
  - drush @pantheon.$PNAME.$PSITE en simpletest -y --strict=0
  - drush @pantheon.$PNAME.$PSITE vset -y simpletest_verbose 0 --strict=0
script:
  # Run real / additional tests here.
  #- drush @pantheon.$PNAME.$PSITE test-run MyTestClass --strict=0
after_script:
  #- drush psite-edelete $PUUID $PSITE -y
  - cd $TRAVIS_BUILD_DIR
  - git push pantheon :$PSITE